### ISSUE TITLE
Linkedin is not validating

### ISSUE THREAD

**Issue by rynebenson** [phbernard/nextjs-linkedIn-insight-tag#1]
When I call the `linkedInTrack` method on events I get window error: `lintrk is not defined`

**Comment by phbernard** [comment]
Old issue, you probably figured it out but just in case...

Did you use `<LinkedInInsightTag />` somewhere in your code? (in your `App` or a layout)? If so, when loading your page, can you see loads from domain `snap.licdn.com` when looking at the network activity?

**Comment by phbernard** [comment]
I close this issue. Please reopen it if you have any news about it.
